events {}
http {
  server {
    listen 8080 default_server;
    listen [::]:8080 default_server;

    server_name learnkube.com;

    location = /learnk8s-logo.svg {
        alias /usr/share/nginx/html/learnk8s-logo.svg;
        add_header Content-Type image/svg+xml;
    }

    location / {
        sub_filter_once off;
        sub_filter " Kubernetes" " Koobernaytis";
        sub_filter ">Kubernetes" ">Koobernaytis";
        sub_filter "linkedin.com/company/LearnKube/" "linkedin.com/company/learnk8sco";
        sub_filter "//learnkube.com" "//learnk8s.co";
        sub_filter ">LearnKube" ">LearnK8s";
        sub_filter '"LearnKube' '"LearnK8s';
        sub_filter " LearnKube" " LearnK8s";
        sub_filter "/LearnKube" "/LearnK8s";
        sub_filter "ready" "bready";
        sub_filter "instructor-led" "Instructor-bled";
        sub_filter " Academy" " Badass Academy";
        sub_filter "hands-on" "Hands-all-over";
        sub_filter "hand" "foot";
        sub_filter " consulting" " consoling";
        sub_filter " training" " straining";
        sub_filter " engineers" " tender ears";
        sub_filter "Daniele Polencic" "D5e 💪";
        sub_filter "Daniele " "D5e 💪 ";
        sub_filter "Miriam Menegatti" "M4m";
        sub_filter "Miriam " "M4m ";
        sub_filter "Chris Nesbitt-Smith" "C3s";
        sub_filter "Chris " "C3s ";
        sub_filter "Alessandro Moretti" "A8o";
        sub_filter "Alessandro " "A8o ";
        sub_filter "Mauricio Salatino" "M6o";
        sub_filter "Mauricio " "M6o ";
        sub_filter "Salman Iqbal" "S4m";
        sub_filter "Salman " "S4m ";
        sub_filter "Gergely Riskó" "G5y";
        sub_filter "Gergely " "G5y ";
        sub_filter "it in production" "the bath";
        sub_filter "in production" "in the bath";
        sub_filter "Engaging" "Boring";
        sub_filter "teach" "Boring";
        sub_filter "subscribe" "unsubscribe immediately";
        sub_filter "deep" "shallow";
        sub_filter "dive" "dip";
        sub_filter " job" " dead end job";
        sub_filter "good" "bad";
        sub_filter "beginner" "idiot";
        sub_filter "work" "sex";
        sub_filter ">Contact" ">Don't contact";
        sub_filter "source" "sauce";
        sub_filter "tools" "fools";
        sub_filter "startups" "endups";
        sub_filter "Fortune 500s" "banging tunes bro!";
        sub_filter "Andrea Giardini" "A4a";
        sub_filter "Andrea " "A4a ";
        sub_filter '<li class="ttu mh2">' '<li class="ttu mh2 bb bn-l b--white"><a href="https://chat.learnk8s.co" class="white link db b ph1 pv3 pv2-l f5 underline-hover" title="Chat">Chat</a></li><li class="ttu mh2 bb bn-l b--white"><a href="https://video.learnk8s.co" class="white link db b ph1 pv3 pv2-l f5 underline-hover" title="Video">Video</a></li><li class="ttu mh2 bb bn-l b--white"><a href="https://shop.learnk8s.co" class="white link db b ph1 pv3 pv2-l f5 underline-hover" title="Shop">Shop</a></li><li class="ttu mh2 bb bn-l b--white"><a href="https://party.learnk8s.co" class="white link db b ph1 pv3 pv2-l f5 underline-hover" title="Party">Party</a></li><li class="ttu mh2">';
        sub_filter "</body>" '<style>.logo { background: url(/learnk8s-logo.svg) no-repeat; background-size: contain; } .logo svg{display:none;}</style><iframe width="560" height="315" src="https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=true" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></body>';
        proxy_redirect     off;
        proxy_ssl_server_name on;
        proxy_set_header Host            learnkube.com;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Accept-Encoding "";
        add_header X-Robots-Tag noindex;
        proxy_pass https://learnkube.com/;
    }
  }
}

